name: Coverage

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  coverage:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --no-fund
      - run: npm run build --if-present
      - run: chmod +x ./dist/bin/cli.js
      - uses: ArtiomTr/jest-coverage-report-action@v2
