name: Coverage

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci --no-fund
      - run: npm run build --if-present
      - run: chmod +x ./dist/bin/cli.js
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
